### PR TITLE
Fix #4 , add initial functionality for domain verification

### LINKED ISSUE #4: Detect too long PW early
I've tried to set this up with a password longer than 72 characters, and it failed to generate the SSH key.
It said something like "more than 72 bytes for OpenSSH keys are not supported" (Forgot to copy the exact error)

I think it should detect this earlier in the script

### PR DESCRIPTION
**Pull request by notthebee**

### CODE REVIEW

File: bootstrap.sh [hunk 1]
```diff
@@ -71,6 +71,12 @@ echo
 echo "Enter your user password"
 echo "This password will be used for Authelia login, administrative access and SSH login"
 read -s -p "Password: " user_password
+until [[ "${#user_password}" -lt 60 ]]; do
```
Comment (D3SOX) [inline bootstrap.sh:74]: Maybe I don't understand this logic but doesn't this mean "if it's less than 60 ask again"

Comment (notthebee) [reply bootstrap.sh:74]: Nope, the opposite. "Until this is less than 60, ask again"

Comment (D3SOX) [reply bootstrap.sh:74]: Ah, thanks for explaining. TIL `until` in bash
